//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EmployeeDetail
    {
        [Required(ErrorMessage ="Please Enter Employee ID")]
        public int Emp_Num { get; set; }
        public string Emp_Name { get; set; }
    }
}
